# File: .github/workflows/publish.yml
name: Refresh

on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  pull_request:
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
